name: frameit_chrome
version: 1.0.0
description: >-
  Embed app store and play store screenshots in device frames.
  Drop in replacement for fastlane frameit.
homepage: https://github.com/authpass/frameit-chrome

executables:
  frameit_chrome: frameit_chrome

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  args: ^2.5.0
  collection: ^1.18.0
  image: ^4.1.7
  json_annotation: ^4.8.1
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1
  meta: '>=1.0.0 <2.0.0'
  path: ^1.7.0
  quiver: ^3.2.1
  supercharged_dart: ^2.1.1
  yaml: ^3.1.2

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.9
  builder_static_text: ^0.1.0
  glob: ^2.1.2
  json_serializable: ^6.7.1
  pedantic: ^1.9.2
  recase: ^4.1.0
  source_gen: ^1.5.0
